[package]
name = 'waysign'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'waysign'

[dependencies]
extendr-api = '0.8.1'
path-tree = '0.8'

[profile.release]
lto = true
codegen-units = 1
